egraphs-good/eggcc

- src/lib.rs
Wanted to start experimenting with some things, noticed that lib.rs wasn't building. I think this is what you meant?
> Fix clippy lint

- README.md
I can never remember how to submodule.
> Add some build/setup instructions to the README for old people

- src/cfg/structured.rs
- src/conversions.rs
- src/lib.rs
> Small cleanups from @ajpal

- src/cfg/mod.rs
- src/cfg/tests.rs
This bug adds a missing edge for implicit returns
> Fix bug in cfg implicit returns

- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
- infra/nightly-resources/table.js
- infra/nightly-resources/utils.js
- infra/nightly.sh
- infra/profile.sh
Now that https://github.com/oflatt/eggcc/pull/18 is in, wire it up to actually be used by the nightly script.
> add profile to nightly webpage

- infra/nightly-resources/index.js
> add # instructions

- infra/nightly.sh
- infra/profile.sh
Some little tweaks to #23 to make it actually work on nightlies
https://nightly.cs.washington.edu/reports/eggcc/1693597289:nightly:profile-nightly:284a8084d6/
> Profile nightly

- src/cfg/mod.rs
There's custom debug output for basic blocks that reconstructs the bril body for the main instructions. This makes the debug output much more readable, but it is missing the content of annotations. This PR adds the annotations back.
> add annotations to debug output for CFG

- src/main.rs
- src/util.rs
This PR adds documentation to `RunType`. It also adds a couple missing ones for debug purposes.
> Document various ways to run eggcc

- src/rvsdg/rvsdg2svg.rs
- src/rvsdg/to_cfg.rs
- tests/snapshots/files__add-peg.snap
- tests/snapshots/files__add-rvsdg.snap
- tests/snapshots/files__add-structured.snap
- tests/snapshots/files__constant_fold_simple-rvsdg.snap
- tests/snapshots/files__diamond-peg.snap
- tests/snapshots/files__diamond-rvsdg.snap
- tests/snapshots/files__diamond-structured.snap
- tests/snapshots/files__fib_shape-rvsdg.snap
- tests/snapshots/files__simple_branch-rvsdg.snap
- tests/snapshots/files__simple_loop-rvsdg.snap
- tests/snapshots/files__unroll_and_constant_fold-rvsdg.snap
This PR fixes a couple bugs. First, in RVSDG->CFG it fixes an arity mismatch. Second, it fixes PRINT visualization in RVSDGS to only have one output port as they should.
I added a reproduction test
> Fix up bug in arities

- Makefile
We were running all our tests in debug mode, which is slow.
> Add release mode flag to make test

- infra/nightly-resources/index.js
- infra/profile.sh
> All Nightlies

- src/rvsdg/egglog_optimizer/gamma_rewrites.egg
- tests/small/gamma_pull_in.bril
- tests/snapshots/files__gamma_pull_in-rvsdg-optimize.snap
- tests/snapshots/files__gamma_pull_in-structured.snap
```
if C:
S1
else:
S2
S3
-----
if C:
S1; S3
else:
S2; S3
```
Right now, special-cased to Plus
Unions a Plus of Projects with a Project of a new Gamma with an output port added that does the Plus within the body of each branch.
> Gamma Pull In

- src/rvsdg/egglog_optimizer/gamma_rewrites.egg
Fix a bug in the rewrite rules and make them operate directly on boolean expressions instead of gamma nodes.
> Fix De Morgan's laws

- uniqueargs/src/main.rs
- uniqueargs/src/schedule.egg
- uniqueargs/src/tests.egg
Small PR that adds infra for adding optimizations.
> Create egglog files for the (run) and (check) statements

- uniqueargs/src/fast_analyses.egg
- uniqueargs/src/main.rs
> Add EVec-get similar to Vec*-get

- tree_unique_args/Cargo.toml
- tree_unique_args/src/main.rs
- tree_unique_args/src/schedule.egg
- tree_unique_args/src/schema.egg
- tree_unique_args/src/tests.egg
- tree_unique_args/tests/interpreter.rs
Adds the schema and a for-reference interpreter for tree semantics + unique args.
1. https://github.com/egraphs-good/eggcc/pull/206
2. https://github.com/egraphs-good/eggcc/pull/212
3. https://github.com/egraphs-good/eggcc/pull/213
4. https://github.com/egraphs-good/eggcc/pull/214
5. https://github.com/egraphs-good/eggcc/pull/216
> [Tree unique] Initial structure for `tree-unique-args`

- tree_unique_args/src/ir.rs
- tree_unique_args/src/main.rs
- tree_unique_args/src/subst.rs
Add rules for the following functions:
```
(function SubstExpr (Expr Expr) Expr)
(function SubstListExpr (ListExpr Expr) ListExpr)
```
1. https://github.com/egraphs-good/eggcc/pull/206
2. https://github.com/egraphs-good/eggcc/pull/212
3. https://github.com/egraphs-good/eggcc/pull/213
4. https://github.com/egraphs-good/eggcc/pull/214
5. https://github.com/egraphs-good/eggcc/pull/216
> [Tree unique] Substitution rules

- tree_unique_args/src/deep_copy.rs
- tree_unique_args/src/ir.rs
- tree_unique_args/src/purity_analysis.rs
- tree_unique_args/src/schema.egg
- tree_unique_args/src/subst.rs
This allows us to union with constants.
> [Tree unique] Add ids to constants

- tree_unique_args/src/deep_copy.rs
- tree_unique_args/src/ir.rs
- tree_unique_args/src/purity_analysis.rs
- tree_unique_args/src/schema.egg
- tree_unique_args/src/subst.rs
- tree_unique_args/src/sugar.egg
Use `(datatype IdSort (Id i64))` instead of `i64` for explicitness.
> [Tree unique] Add id sort

- tree_unique_args/src/body_contains.rs
- tree_unique_args/src/main.rs
Very similar to https://github.com/egraphs-good/eggcc/pull/143.
Adds relations:
```
(relation BodyContainsExpr (Expr Expr))
(relation BodyContainsListExpr (Expr ListExpr))
```
> [Tree unique] Add `BodyContains`

- tree_unique_args/src/main.rs
- tree_unique_args/src/util.egg
- tree_unique_args/src/util.rs
Add util.egg, which contains ListExpr-length and ListExpr-ith function.
> Add util.egg

- tree_unique_args/src/main.rs
- tree_unique_args/src/simple.rs
- tree_unique_args/src/switch_rewrites.rs
Accidentally merged https://github.com/egraphs-good/eggcc/pull/229 with cargofmt errors
> sorry, cargo fmt!

- tree_unique_args/src/purity_analysis.rs
Fix a small bug of purity of Call in purity analysis. Previously the purity of Call don't consider the purity of Function itself.
> fix function purity analysis

- tree_unique_args/src/type_analysis.egg
- tree_unique_args/src/type_analysis.rs
> Add context to type analysis

- tree_unique_args/Cargo.lock
- tree_unique_args/Cargo.toml
- tree_unique_args/src/interpreter.rs
> I64 fresh new commit

- tree_assume/src/schema.egg
> fix comment in schema

- tree_assume/src/schema_helpers.rs
Add metaprogramming similar tree-unique's `ir.rs` to tree-assume.
---
PR stack:
1. #336
2. #337 
3. #338 
3. #339
> [Tree assume] Add metaprogramming tooling

- tree_assume/src/lib.rs
- tree_assume/src/optimizations/is_valid.rs
- tree_assume/src/optimizations/mod.rs
Add `IsValid` to tree-assume. See #262.
---
PR stack:
1. #336
2. #337 
3. #340 
4. #338 
3. #339
> [Tree assume] Add `IsValid`

- tree_assume/src/lib.rs
- tree_assume/src/optimizations/body_contains.rs
- tree_assume/src/optimizations/mod.rs
Add `IsValid` to tree-assume. See #226.
---
PR stack:
1. #336
2. #337 
3. #340 
4. #338 
3. #339
> [Tree assume] Add `BodyContains`

- tree_assume/src/schedule.egg
- tree_assume/src/schema.egg
- tree_assume/src/type_analysis.egg
- tree_assume/src/type_analysis.rs
More to come including tests for error cases, but this was already kind of tricky so it's probably worth starting review now.
> Start loops

- src/cfg/to_bril.rs
- src/rvsdg/tests.rs
- src/rvsdg/to_cfg.rs
- src/util.rs
Wire in memory ops in to_cfg. Opening a draft as there are a few questions in to_cfg I'd like to resolve.
Fixes #343
> Memory ops for RVSDG => Bril

- tree_assume/src/lib.rs
- tree_assume/src/optimizations/mod.rs
- tree_assume/src/optimizations/purity_analysis.rs
- tree_assume/src/schema.rs
- tree_assume/src/schema_helpers.rs
- tree_assume/src/utility/mod.rs
Add `IsPure` to tree-assume. See #212.
Merge after #340.
> [Tree assume] Add `IsPure`

- tree_assume/src/optimizations/purity_analysis.rs
- tree_assume/src/type_analysis.rs
- tree_assume/src/utility/subst.rs
I merged #354 with a successful CI build, but at the same time we merged some new tests in the egglog typechecker.
This PR fixes the resulting conflicts.
> Fix build on main due to conflicting PRs

- tree_in_context/src/interpreter.rs
- tree_in_context/src/lib.rs
- tree_in_context/src/optimizations/constant_fold.rs
- tree_in_context/src/optimizations/mod.rs
- tree_in_context/src/optimizations/switch_rewrites.egg
- tree_in_context/src/optimizations/switch_rewrites.rs
- tree_in_context/src/schedule.egg
This PR adds switch rewrites and switch rewrite tests. It also fixes an interpreter bug with short circuiting.
> Three quarters switch rewrites

- infra/nightly-resources/index.html
- infra/profile.sh
The old rvsdg-optimize was removed
> Make nightly run rvsdg-roundtrip

- infra/aggregate.py
- infra/profile.sh
Still to do:
- add other run-modes (eggcc + brilift, eggcc only, brillvm)
- clean up the UI
> [Nightly] Benchmark brilift executables

- dag_in_context/src/optimizations/conditional_invariant_code_motion.rs
See also https://github.com/egraphs-good/eggcc/pull/381.
Example rewrite (arg and const types elided for brevity):
```
(If
(Get (Arg) 2)
(Bop (LessThan) (Get (Arg) 0) (Const (Int 7)))
(Bop (LessThan) (Get (Arg) 1) (Const (Int 7))))
~~>
(Bop (LessThan)
(If
(Get (Arg) 2)
(Get (Arg) 0)
(Get (Arg) 1))
(Const (Int 7)))
```
Example generated rule:
```
(rewrite (If c (Bop _op _x e1) (Bop _op _x e2))
(Bop _op _x (If c e1 e2))
:when ((ExprIsValid (If c (Bop _op _x e1) (Bop _op _x e2))))
:ruleset conditional-invariant-code-motion)
```
> [DAG In Context] CICM for `If`

- Cargo.lock
- Cargo.toml
Now that https://github.com/sampsyo/bril/pull/315 is merged, we shouldn't depend on my fork anymore.
> Switch back to main bril

- src/util.rs
All the tests pass on my machine.
> add workaround for new macos linker

- infra/profile.py
- src/util.rs
rvsdg round trip to executable
> new runmode for nightly

- dag_in_context/src/utility/util.egg
- dag_in_context/src/utility/util.rs
Copy Kevin's SubTuple into another pull request so we can merge it first
> SubTuple (tuple of gets)

- dag_in_context/src/greedy_dag_extractor.rs
- tests/snapshots/files__collatz-optimize.snap
- tests/snapshots/files__collatz_redundant_computation-optimize.snap
- tests/snapshots/files__fib-optimize.snap
- tests/snapshots/files__fib_recursive-optimize.snap
- tests/snapshots/files__flatten_loop-optimize.snap
- tests/snapshots/files__gamma_condition_and-optimize.snap
- tests/snapshots/files__implicit-return-optimize.snap
- tests/snapshots/files__loop_if-optimize.snap
- tests/snapshots/files__nested_call-optimize.snap
- tests/snapshots/files__reassoc-optimize.snap
- tests/snapshots/files__simple-call-optimize.snap
- tests/snapshots/files__simple_call-optimize.snap
- tests/snapshots/files__simple_recursive-optimize.snap
- tests/snapshots/files__strong_loop-optimize.snap
- tests/snapshots/files__unroll_and_constant_fold-optimize.snap
This PR optimizes the extraction algorithm to scale to medium-sized benchmarks.
It uses a parent table, similar to extraction algorithms in the extraction-gym
> Optimize extraction algorithm using worklist, enabling medium-sized benchmarks

- Makefile
- src/util.rs
- tests/files.rs
> Move exes to /tmp

- dag_in_context/src/ast.rs
- dag_in_context/src/schema.rs
- dag_in_context/src/schema_helpers.rs
- dag_in_context/src/to_egglog.rs
- dag_in_context/src/utility/mod.rs
- dag_in_context/src/utility/wildcard.rs
Add an Assumption wildcard for query so no need to construct the Assumption in testing.
> Add Assumption wildcard

- dag_in_context/src/lib.rs
- dag_in_context/src/main.rs
- dag_in_context/src/schedule.rs
Add schedule to the output so cargo run contain schedule
> Add schedule to main

- tests/passing/small/gamma_condition_and.bril
- tests/snapshots/files__gamma_condition_and-optimize.snap
Changes the bril test that I wrote for the milestone to test the new 3/4 optimizations.
> Bril test for 3/4 if optimizations

- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
> add all/none buttons

- dag_in_context/src/greedy_dag_extractor.rs
- dag_in_context/src/schema.egg
* Add a test case where first extraction failed but second succeed
* Don't do second extraction if the first one is successful
> Small improvements to extraction

- Makefile
- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
- infra/nightly-resources/stylesheet.css
- infra/nightly-resources/table.js
Functional changes:
1. Make diff + checkboxes interact correctly (this was broken by https://github.com/egraphs-good/eggcc/pull/516)
2. Hide warnings by default
Code structure changes:
1. move event handling logic into handlers.js
2. Separate data fetching logic from rendering logic
3. Autoformat everything and enforce formatting in the Makefile
4. Be more clear about what the global/persistent data structure is
> Nightly cleanup

- infra/nightly-resources/Plugin.Errorbars.js
- infra/nightly-resources/chart.js
- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
Also makes benchmarks toggleable:
So that you can look at the graph for one benchmark at a time, which is helpful for scaling reasons:
> Add chart to nightly

- infra/nightly-resources/chart.js
- infra/nightly-resources/index.js
> Sort benchmarks in chart

- dag_in_context/src/greedy_dag_extractor.rs
Increases the cost of Call to allow more inlinings.
> Increase Call cost

- dag_in_context/src/optimizations/passthrough.egg
- src/util.rs
- tests/passing/small/if_dead_code.bril
- tests/snapshots/files__fib_shape-optimize.snap
- tests/snapshots/files__flatten_loop-optimize.snap
- tests/snapshots/files__if_dead_code-optimize.snap
- tests/snapshots/files__implicit-return-optimize.snap
- tests/snapshots/files__small-fib-optimize.snap
Also deletes the theta passthrough comment because Oliver implemented it on his branch.
> Make if predicate passthrough destructively rewrite

- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
- infra/nightly-resources/llvm.html
- infra/profile.py
- src/util.rs
Link in the table:
Opens in a new tab:
> Add llvm output to nightly

- dag_in_context/src/optimizations/loop_strength_reduction.egg
- tests/snapshots/files__strong_loop-optimize.snap
This PR fixed a bug in loop strength reduction. Looks like we mixed up two indices
I also refactored it slightly so that we don't create invalid terms
> Fix bug in strength reduction

- Cargo.lock
- Cargo.toml
- dag_in_context/src/ast.rs
- dag_in_context/src/from_egglog.rs
- dag_in_context/src/greedy_dag_extractor.rs
- dag_in_context/src/interpreter.rs
- dag_in_context/src/linearity.rs
- dag_in_context/src/optimizations/purity_analysis.rs
- dag_in_context/src/schema.egg
- dag_in_context/src/schema.rs
- dag_in_context/src/schema_helpers.rs
- dag_in_context/src/typechecker.rs
- src/rvsdg/from_dag.rs
- src/rvsdg/to_dag.rs
- tests/snapshots/files__fib_recursive-optimize.snap
- tests/snapshots/files__gamma_condition_and-optimize.snap
- tests/snapshots/files__loop_pass_through-optimize.snap
- tests/snapshots/files__reassoc-optimize.snap
Going to close https://github.com/egraphs-good/eggcc/pull/565, I'm not sure what exactly is going on in that PR, but one of the other little changes I made in that diff must be slowing down the CI.
> Add `select` operator

- infra/nightly-resources/chart.js
- infra/nightly-resources/data.js
- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
- infra/nightly-resources/llvm.html
- infra/nightly-resources/previousRuns.js
- infra/nightly-resources/stylesheet.css
- infra/nightly-resources/utils.js
> Big ol nightly refactor

- infra/nightly-resources/chart.js
- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
Normalized to `llvm-peep` (can make this selectable if we want?)
> Add speedup chart

- infra/nightly-resources/data.js
- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/stylesheet.css
- infra/nightly-resources/table.html
@ryan-berger I don't think the latex is correct here.. When I copy it into overleaf I get all kinds of errors:
> Add warning for missing llvm and render table latex

- infra/nightly-resources/chart.js
- infra/nightly-resources/handlers.js
- infra/nightly-resources/index.html
- infra/nightly-resources/stylesheet.css
Also puts a scrollbox on the benchmarks so it's more manageable:
> Show baseline as dotted line at 1 for speedup

- infra/generate_cfgs.py
This PR fixes the opt detection hack on the leviathan machine by passing the version flag
> Opt fix by passing version flag

- src/util.rs
The nightly doesn't get worse!
> Enable vectorization for llvm again

- infra/graphs.py
- infra/nightly-resources/index.html
- infra/nightly-resources/index.js
> Latex macro for percent of benchmarks where we recover 80% of the performance improvement that llvm finds

- infra/nightly-resources/chart.js
- infra/nightly-resources/data.js
- infra/nightly-resources/index.js
- infra/profile.py
> eggcc-o3-o3 run mode

- dag_in_context/src/lib.rs
- infra/graphs.py
- infra/nightly-resources/data.js
- infra/profile.py
- src/util.rs
> Add extraction time to nightly

- infra/nightly.sh
This PR moves eggcc to a new "auto-upload" feature in the nightlies; it should be merged after https://github.com/uwplse/nightly-conf/pull/20.
> Move eggcc to auto-upload
