Cargo.toml, src/cfg/mod.rs, src/cfg/tests.rs, src/cfg/to_structured.rs, src/conversions.rs, src/lib.rs, src/rvsdg/from_cfg.rs, src/rvsdg/live_variables.rs, src/rvsdg/mod.rs, src/rvsdg/restructure.rs, src/rvsdg/rvsdg2svg.rs, src/rvsdg/tests.rs, src/util.rs
This PR provides initial support for conversion from bril to RVSDGs, including a restructuring pass that converts unstructured CFGs into structured ones. Missing are:
* Support for side-effects (like memory, or print)
* An egglog representation, though this PR unblocks Yihong's work on this front.
* Translation back into a CFG.
Translation back into a CFG will allow us to increase test coverage more: there are unit tests here, but writing unit tests manually is error-prone and time-consuming. Adding more translation functions will let us automate tests for larger / trickier examples.
=> Initial RVSDG support

src/lib.rs, src/peg/mod.rs, src/peg/simulate.rs, src/peg/tests.rs, src/rvsdg/mod.rs
This PR:
- Creates a Rust representation of PEGs (heavily inspired by the RVSDG encoding).
- Adds a method to convert Rust RVSDGs to Rust PEGs. (This was done so that there wouldn't be two different CFG -> Dataflow functions. However, it does mean that the PEGs are occasionally inefficient because RVSDG theta nodes are currently do-while/tail-controlled, so the translation requires unrolling the theta nodes an extra step.)
- Adds a method to simulate (interpret) a PEG.
- Adds a method to write a PEG out as a .dot file (although ordering of children isn't preserved so it''s slightly misleading).
- Adds some tests for the PEG conversion that mirror the RVSDG tests.
=> PEGs in Rust

src/peg/mod.rs, src/peg/peg2dot.rs, src/peg/simulate.rs, src/peg/tests.rs, src/util.rs
This PR:
- Adds a PegProgram struct to mirror RVSDGs.
- Makes PegFunction::graph preserve orderings of its children (there's an ordering attribute).
- Adds pegs to the DebugVisualization struct. I think I did this right, but RVSDG viz wasn't working on the files I tested, and so PEG viz didn't work either.
=> Peg visualization cleanup

Cargo.toml, src/conversions.rs, src/lib.rs, tests/snapshots/files__add_naiive.snap, tests/snapshots/files__add_naiive_no_opt.snap, tests/snapshots/files__block-diamond_naiive.snap, tests/snapshots/files__block-diamond_naiive_no_opt.snap, tests/snapshots/files__diamond_naiive.snap, tests/snapshots/files__diamond_naiive_no_opt.snap, tests/snapshots/files__two_fns_naiive_no_opt.snap
Quite a bit of refactoring along the way. This PR is a draft until egraphs-good/egglog#207, egraphs-good/egglog#213, and egraphs-good/egglog#214 are merged.
Until then, it's not easy to test this locally, but here's the punchline:
``` text
pub(crate) fn term_to_type(&self, id: &TermId) -> Type {
modified   tests/snapshots/files__add.snap
@@ -10,8 +10,7 @@ expression: "format!(\"{}\", res)"
v0.0: int = const 1;
v1.0: int = const 2;
v2.0: int = const 3;
-  v0_: int = const 3;
-  print v0_;
+  print v2.0;
ret;
.sblock___1:
.exit___:
modified   tests/snapshots/files__add_no_opt.snap
@@ -9,13 +9,8 @@ expression: "format!(\"{}\", res)"
.b1:
v0.0: int = const 1;
v1.0: int = const 2;
-  v0_: int = const 1;
-  v1_: int = const 2;
-  v2.0: int = add v0_ v1_;
-  v3_: int = const 1;
-  v4_: int = …
```
=> Memoize expressions in basic blocks

Cargo.toml
Larger diff because this changed the peg visualizations. Spot-checks look reasonable.
=> bump egglog revision

Cargo.toml, src/lib.rs, src/rvsdg/schema.egg, src/rvsdg/tests.rs
Adds the following functions, for use in writing passes over RVSDG
```
;;                   e  [ x -> v ]
(function SubstExpr (Expr i64 Operand) Expr)
(function SubstOperand (Operand i64 Operand) Operand)
(function SubstBody (Body i64 Operand) Body)
(function SubstVecOperand (VecOperand i64 Operand) VecOperand)
(function SubstVecVecOperand (VecVecOperand i64 Operand) VecVecOperand)
```
Updated the egglog revision we depend on as this feature relies on `vec-set`: https://github.com/egraphs-good/egglog/pull/239
Added tests to [`src/rvsdg/tests.rs`](https://github.com/rtjoa/eggcc/blob/subst/src/rvsdg/tests.rs)
=> Add RVSDG subst functions

src/main.rs, src/peg/simulate.rs, tests/small/fib_shape.bril
This PR cleans up and then speeds up the PEG interpreter. It is now fast enough to run the fib-shape test with n=10 as part of the test suite. It's still honestly not that fast, but I don't think it needs to be faster than it is now for the foreseeable future.
=> PEG Interpreter Memoization

src/peg/mod.rs, src/peg/peg2dot.rs, src/peg/simulate.rs, src/peg/tests.rs, src/rvsdg/from_cfg.rs, src/rvsdg/from_egglog.rs, src/rvsdg/mod.rs, src/rvsdg/rvsdg2svg.rs, src/rvsdg/tests.rs, src/rvsdg/to_cfg.rs, src/rvsdg/to_egglog.rs
`RvsdgExpr` is also used in pegs, so it's a bad name
I don't like `Expr` because it conflicts with bril
=> Rename RvsdgExpr to BasicExpr

src/cfg/tests.rs, src/peg/peg2dot.rs, src/peg/simulate.rs, src/rvsdg/egglog_optimizer/schema.egg, src/rvsdg/from_cfg.rs, src/rvsdg/from_egglog.rs, src/rvsdg/mod.rs, src/rvsdg/tests.rs, src/rvsdg/to_egglog.rs
* Function names should be a string instead of Identifier.
* Function call in RVSDG should support effects and void return type.
* fix the egglog to RVSDG conversion to have the right number of arguments.
* Function call returns {1, 2} values, where the first value is the state edge, and the second one (optional) is the actual return value.
=> Supporting multiple functions (Part I): fixing function calls in egglog's encoding of RVSDG

src/peg/simulate.rs
Fixes #59.
Phi nodes were being evaluated eagerly, now they're not.
=> Fix eager PEG phi node eval

src/rvsdg/egglog_optimizer/mod.rs, src/rvsdg/egglog_optimizer/shift.egg, src/rvsdg/tests.rs
Adds the following functions, for use in writing passes over RVSDG.
```
;; Within e, replace all (Args x) where x > last-unshifted
;; with (Args (x + amt))
;;                             e             last-unshifted  amt
(function ShiftExpr           (Expr          i64             i64) Expr)
(function ShiftOperand        (Operand       i64             i64) Operand)
(function ShiftBody           (Body          i64             i64) Body)
(function ShiftVecOperand     (VecOperand    i64             i64) VecOperand)
(function ShiftVecVecOperand  (VecVecOperand i64             i64) VecVecOperand)```
```
The rules that execute them are placed in ruleset `shift`.
Added tests to [`src/rvsdg/tests.rs`](https://github.com/rtjoa/eggcc/blob/subst/src/rvsdg/tests.rs)
=> Add RVSDG shift rules

src/util.rs, tests/files.rs
This PR changes `run` to only interpret the original program if the interp flag is passed. Before, it would interpret the original program but not the result program if the interp flag was not passed.
=> Don't interpret original program unless --interp passed

src/rvsdg/egglog_optimizer/mod.rs, src/rvsdg/egglog_optimizer/reassoc.rs, tests/small/reassoc.bril, tests/snapshots/files__implicit-return-rvsdg-optimize.snap, tests/snapshots/files__reassoc-peg.snap, tests/snapshots/files__reassoc-rvsdg-optimize.snap, tests/snapshots/files__reassoc-structured.snap
This PR re-associates additions, moving constants to the left.
Future work will include adding support for multiplication and pruning e-classes that are constant.
I think this is good enough to close #93 for our milestone.
=> Re-associate additions to promote constant folding

src/rvsdg/from_cfg.rs, tests/small/flatten_loop.bril, tests/snapshots/files__flatten_loop-rvsdg-optimize.snap, tests/snapshots/files__flatten_loop-structured.snap
We were getting inconsistent answers for join points because a loop back-edge was "tricking" the join point algorithm into stopping early. The fix is to just filter out back-edges using the usual algorithm of scanning the dominators.
Fixes #130
=> Exclude loop back-edges when finding join points.

src/rvsdg/egglog_optimizer/fast_analyses.rs, src/rvsdg/egglog_optimizer/mod.rs, src/rvsdg/egglog_optimizer/subst.rs, src/rvsdg/tests.rs
Add `(relation TYPE-is-pure (TYPE))` where `TYPE` is one of `{Expr, Body, Operand, VecOperand, VecVecOperand}`.
We consider something pure if interpreting it wouldn't print anything, e.g. a function that passes around a print edge but never uses it would still be considered pure.
We also do some minor refactoring, moving vector reification into the `fast-analyses` ruleset - meant for frequently-used, at-most-linear-time analyses (e.g. this one).
=> Add purity analysis

src/rvsdg/egglog_optimizer/fast_analyses.rs, src/rvsdg/tests.rs
Add `(relation Body-contains-TYPE (Body i64 TYPE))` where `TYPE` is one of `{Expr, Body, Operand}`. If we call the arguments `body`, `i`, and `e`, a tuple of one of these relations indicates that `body` contains `e` in its `i`th output.
A Body is considered to contain something if it's in the Body's context. Notably, if a Gamma/Theta contains `x`, then the Args in `x` must be bound by that Gamma/Theta.
To get the intuition:
- A region containing a Gamma will contain that Gamma's inputs and predicate.
- A region containing a Theta will contain that Theta's inputs.
- A Gamma contains its own outputs.
- A Theta contains its own predicate and outputs.
=> Add `Body-contains-*` rules

src/rvsdg/tests.rs
Fixes #148 so that it is not deleted.
=> Fix rvsdg_odd_branch_egg_roundtrip test

src/rvsdg/egglog_optimizer/interval-analysis.egg, src/rvsdg/egglog_optimizer/loop-optimizations.egg, src/rvsdg/egglog_optimizer/mod.rs, src/rvsdg/egglog_optimizer/passthrough_optimize.rs, tests/snapshots/files__block-diamond-rvsdg-optimize.snap, tests/snapshots/files__collatz-rvsdg-optimize.snap, tests/snapshots/files__eliminate_gamma_interval-rvsdg-optimize.snap, tests/snapshots/files__fib_shape-rvsdg-optimize.snap, tests/snapshots/files__flatten_loop-rvsdg-optimize.snap, tests/snapshots/files__gamma_condition_and-rvsdg-optimize.snap, tests/snapshots/files__implicit-return-rvsdg-optimize.snap
This PR is blocked on subst rules not saturating when there is a cycle.
It also relies on the argument that unioning a project with something else is valid when the whole thing is pure.
The non-pure version is much harder.
=> Optimize passed through arguments, but only in the pure case

src/rvsdg/egglog_optimizer/subst.rs, src/rvsdg/tests.rs
Rather than an abritrary body, have `above` in `can-TYPE-subst-beneath` (#111) take a `Context`:
```
(datatype Context
(GammaCtx VecOperand)
(ThetaCtx VecOperand))
```
Where one would previously write:
`(can-subst-TYPE-beneath (Gamma pred inputs outputs) from to)`
One now writes:
`(can-subst-TYPE-beneath (GammaCtx inputs) from to)`
And likewise for `Theta`. This allows some to subst beneath one body but not another if they differ in inputs, even if they are unioned.
=> Have `can-subst-beneath` take `Context` rather than `Body`

src/rvsdg/egglog_optimizer/conditional_invariant_code_motion.egg, src/rvsdg/egglog_optimizer/mod.rs, src/rvsdg/egglog_optimizer/subst.rs, src/rvsdg/tests.rs, tests/small/branch_duplicate_work.bril, tests/snapshots/files__branch_duplicate_work-rvsdg-optimize.snap, tests/snapshots/files__branch_duplicate_work-structured.snap
If all branches of a `Gamma` share code, we can compute it outside the body and pass the result via a new argument.
Example:
| Unoptimized  | Optimized |
| ------------- | ------------- |
| ![image](https://github.com/oflatt/eggcc/assets/51928404/b3b3da69-2b86-411a-b8f4-da3cde6dda15) | ![image](https://github.com/oflatt/eggcc/assets/51928404/171d75a2-7048-441d-a982-cb0e59d11f77) |
As this uses `can-subst-beneath`, which is slow/doesn't saturate, we move it to its own ruleset, `subst-beneath`, and modify the schedule to use it more sparingly. In the future we hope to improve `can-subst-beneath` (contextual equality, named wires), separately from this PR.
Added Bril test at `tests/small/branch_duplicate_work.bril` and RVSDG-level tests at `src/rvsdg/tests.rs`.
=> Conditional invariant code motion

src/rvsdg/egglog_optimizer/subst.rs
`can-subst-*-beneath` would get stopped by a PRINT because there was no rule to propagate it through a print.
=> Add print rules to can-subst-beneath

src/rvsdg/egglog_optimizer/mod.rs, src/rvsdg/egglog_optimizer/subst.rs, src/rvsdg/tests.rs
Before, 20 iterations of `subst-beneath` OOM'd after 15min on my computer. With this change, it takes ~30 seconds.
We conservatively increase the number of iters from 6 to 10.
Thanks to @yihozhang for originally suggesting this optimization!
=> Optimize `can-subst-beneath` by checking whether `new-from` is in `above` before creating new tuple

src/rvsdg/egglog_optimizer/util.egg
It should reduce the number of VecOperand generated and reduce the VecOperand-get table.
=> Change PassThroughArgumentsHelper to VecOperandBase

src/rvsdg/egglog_optimizer/subst.rs, tests/snapshots/files__range_check-rvsdg-optimize.snap, tests/snapshots/files__range_splitting-rvsdg-optimize.snap
Last Tuesday in hackathon we found that VecOperand-get table's rules are firing too many times in some cases, which implies too many VOs are created. A possible cause is subst's helper methods are creating VO/VVOs every iteration. This PR changes the helper only creating new VOBases in iterations. 
actually it reduces test time by about 1s on my computer.
and it makes the (repeat 1000 subst) in mod.rs line 78 able to saturate, though IDK if it's good idea to make it saturate.
=> Make SubstVec*-helpers not to create unnecessary VO/VVO/VOCs

uniqueargs/src/deep_copy.egg
This makes DeepCopy work with constants having ids. (I think the version in #200 is wrong.)
=> Fix DeepCopy bug

uniqueargs/src/deep_copy.egg, uniqueargs/src/main.rs, uniqueargs/src/schedule.egg, uniqueargs/src/schema.egg, uniqueargs/src/switch_rewrites.egg, uniqueargs/src/switch_rewrites.rs, uniqueargs/src/tests.egg, uniqueargs/src/util.egg
This PR adds the two switch optimizations that simplify predicates.
It also contains a bunch of refactors, such as adding saturated rulesets and creating a `util.egg` file.
It also makes `DeepCopy` `unextractable`; I believe this is correct but would like to double check.
Currently missing tests.
=> Unique args switch rewrites

tree_unique_args/src/deep_copy.rs, tree_unique_args/src/ir.rs, tree_unique_args/src/main.rs, tree_unique_args/src/sugar.egg
Add rules for the following functions:
```
(function DeepCopyExpr (Expr i64) Expr)
(function DeepCopyListExpr (ListExpr i64) ListExpr)
(function NewLoop (i64 Expr Expr) Expr)
(function NewLet (i64 Expr Expr) Expr)
```
1. https://github.com/egraphs-good/eggcc/pull/206
2. https://github.com/egraphs-good/eggcc/pull/212
3. https://github.com/egraphs-good/eggcc/pull/213
4. https://github.com/egraphs-good/eggcc/pull/214
5. https://github.com/egraphs-good/eggcc/pull/216
=> [Tree unique] `DeepCopy`, `NewLoop`, `NewLet`

tree_unique_args/src/util.egg, tree_unique_args/src/util.rs
Add the function `Append (ListExpr Expr)` to add an expression to the end of a list. This is useful for adding new inputs/outputs.
=> Add Append util for ListExpr

src/cfg/mod.rs, src/rvsdg/optimize_direct_jumps.rs, src/util.rs, tests/repro-directjumps.bril
We use `optimize_direct_jumps` to clean up cfgs that are generated by translation passes. It was fairly un-tested, and this PR fixes a bug where the footer wasn't getting copied over to the new cfg.
=> Fix a bug in `optimize_direct_jumps` and add testing

tree_unique_args/src/conditional_invariant_code_motion.rs, tree_unique_args/src/function_inlining.egg, tree_unique_args/src/function_inlining.rs, tree_unique_args/src/is_valid.rs, tree_unique_args/src/main.rs, tree_unique_args/src/should_be_valid.rs, tree_unique_args/src/switch_rewrites.rs
Adds the following relations, which indicate that we expect some IR to be well-formed (typecheck, proper use of referencing and capturing ids).
```
(relation ExprIsValid (Expr))
(relation ListExprIsValid (ListExpr))
```
All optimizations that add to the e-graph should first match on these relations, to make sure we optimize code we care about, and not intermediary terms that still need to be substed or copied. This has the following benefits:
- Preserve invariants - it prevents provenance of an Expr term from having semantics, which makes [soundness of our capturing id invariants](https://gist.github.com/rtjoa/a28a0dd7b16da2f4a5a414ad8c4c7127/) easier.
- Performance - when we only optimize `IsValid` expressions, we avoid wasting time on intermediary to-be-copied-or-substed expressions, …
=> [Tree unique] Add `{Expr,ListExpr}IsValid` & update existing optimizations

Cargo.lock, Cargo.toml, src/rvsdg/mod.rs, src/rvsdg/tree_unique/mod.rs, tree_unique_args/Cargo.lock, tree_unique_args/Cargo.toml, tree_unique_args/src/body_contains.rs, tree_unique_args/src/conditional_invariant_code_motion.rs, tree_unique_args/src/interpreter.rs, tree_unique_args/src/is_valid.rs, tree_unique_args/src/lib.rs, tree_unique_args/src/main.rs, tree_unique_args/src/purity_analysis.rs, tree_unique_args/src/subst.rs, tree_unique_args/src/util.rs
This PR makes a `lib.rs` in the tree unique crate so that we can export the grammar. My plan is to connect the "front end" crate to the "back end" tree-unique-args crate.
=> Reorganize files in preparation for Rvsdg -> Tree translation

tree_unique_args/src/id_analysis.rs, tree_unique_args/src/lib.rs, tree_unique_args/src/schedule.egg, tree_unique_args/src/simple.rs, tree_unique_args/src/switch_rewrites.rs
Creates relations `ExprHasRefId`, `ListExprHasRefId` to find the referencing id of an expression (the id of the context containing the expression).
=> [Tree unique] Referencing Id Analysis

.gitignore, tree_unique_args/src/ivt.egg, tree_unique_args/src/ivt.rs, tree_unique_args/src/lib.rs, tree_unique_args/src/schedule.egg, tree_unique_args/src/sugar.egg
This is my attempt at #244 
The rules are a lot simpler than in the milestone encoding. That's due to the encoding itself being easier to write rules for, and also because the rule itself only matches loops whose body is "just a switch." I think we want to have rules that push computations _inside_ switches in order to expose opportunities to IVT (we already have some of these).
Marking this as a draft as I'm not sure about the best way to re-assign expressions' ids (e.g. within `Num`s) to ids from the outer scope. The test gives an example (see the `TODO`) of a case where the `Num`s retain the id from the old loop. I figure this is something that's come up before and I'd appreciate guidance on on the cleanest way to do it.
=> [TreeUnique] IVT

tree_unique_args/src/lib.rs, tree_unique_args/src/sugar.egg, tree_unique_args/src/util.egg, tree_unique_args/src/util.rs
This PR add Expr-size rules that compute the size of a Expr, which Loop invariant hoisting depends on.
Something I'm concerning is what should be counted. I don't count the Cons and Nil constructor in List, and also don't count the Get and All constructor. Alternative interpretations could be:
- Any constructor is counted. 
- Only things that have cost of computation will be counted, which will remove the size of Let, Num, Bool, Arg, and cost of Switch should be size (or cost?) of pred + max cost of branches.
- It could also change to Expr-cost instead of size, which give each operation different cost. (or have Expr-size and Expr-cost at same time)
=> Add Expr-size

src/rvsdg/tree_unique/to_tree.rs, tree_unique_args/src/ast.rs
This PR implements the translation of a function with a single region to the tree encoding. It doesn't run the interpreter or optimizations on the result yet.
=> Translate a single region from RVSDG to tree encoding

src/rvsdg/tree_unique/to_tree.rs, tree_unique_args/src/ast.rs
Extends the translation from RVSDG to translate loops, and adds two tests.
Makes some convenient macros for constructing asts.
=> Translate RVSDG loops to tree encoding 

tree_unique_args/src/body_contains.rs
This PR fix the issue #299 that 
c ≅ (Let id1 (arg1 = 1) arg1+arg1) ≅ (Let id2 (arg2 = 2) arg2)   resulting in
(BodyContains c (+ arg1 arg1)) and (BodyContains c arg2)
I perfer to still call it BodyContains, which seems more intuitive.
=> Change (BodyContain Expr Expr) to (BodyContain Id Expr)

tree_optimizer/src/ast.rs, tree_optimizer/src/error_checking.rs, tree_optimizer/src/expr.rs, tree_optimizer/src/interpreter.rs, tree_optimizer/src/ir.rs, tree_optimizer/src/schema.egg, tree_optimizer/src/util.rs
This PR adds `If` so that we can differentiate it from `Switch`. Now when the predicate is a boolean, `If` must be used.
=> Add If to schema

tree_assume/src/schema.egg, tree_assume/src/schema.rs
See diff here:
https://github.com/egraphs-good/eggcc/compare/main..oflatt-assume-rust
Github uses "three dot" diff by default but we need a "two dot" diff to just see changes
=> Assume schema in rust

tree_assume/src/ast.rs, tree_assume/src/lib.rs, tree_assume/src/schedule.egg, tree_assume/src/schema.egg, tree_assume/src/schema.rs, tree_assume/src/schema_helpers.rs, tree_assume/src/to_egglog.rs, tree_assume/src/utility/assume.egg, tree_assume/src/utility/assume.rs, tree_assume/src/utility/mod.rs
This PR adds some elegant rules that propagate assume nodes down from a top-level function. It also adds a couple of tests.
Not included is rules for `Switch`, which are a little harder.
This PR changes `Assumption` to have *three* new variants: `InIf` and `InFunction`, and `InSwitch`.
I realized that our previous plan of using a strait up boolean condition isn't quite right due to effects. For example, if an `If` statement reads from memory, the value it reads is whatever was in memory at the execution time of the predicate.
=> Add rules that propogate assume nodes to create unique contexts

tree_assume/src/lib.rs, tree_assume/src/main.rs
Improve test debugging workflow by printing both schema and error on test failure, and printing schema on `cargo run`.
---
PR stack:
1. #336
2. #337 
3. #338 
3. #339
=> [Tree assume] Print schema on test failure and `cargo run`

tree_assume/src/to_egglog.rs
Get doesn't take a const, it just takes a literal i64.
This behavior is exercised in a follow-up PR.
---
PR stack:
1. #336
2. #337 
3. #340 
4. #338 
3. #339
=> [Tree assume] Fix get's to_egglog

tree_in_context/src/type_analysis.egg, tree_in_context/src/type_analysis.rs
This PR fixes a bug in `HasArgType`.
For expressions that don't reference arg, they may have any arg type. I added a test case that demonstrates this.
The fix is to only have an error when we infer a different arg type for a reference to the argument.
=> Fix bug in HasArgType

src/rvsdg/tree_unique/to_tree.rs, src/util.rs
This PR modifies the translation from RVSDG to tree encoding to not generate let bindings for pure expressions.
=> Don't generate let bindings for pure expressions

tree_in_context/src/interpreter.rs, tree_in_context/src/lib.rs, tree_in_context/src/optimizations/loop_simplify.egg, tree_in_context/src/schedule.egg, tree_in_context/src/typechecker.rs, tree_in_context/src/utility/in_context.egg, tree_in_context/src/utility/in_context.rs
Creating new contexts is a subtle thing to get right.
This PR proposes that the automatic rules only create contexts with context-free children. Without this change, rules never saturate even for non-cyclic egraphs due to InLoop.
We should keep thinking about what contexts to create and how rules can indicate contexts to create.
=> Create new contexts with only context-free children

infra/profile.sh, src/main.rs, src/rvsdg/from_tree.rs, src/rvsdg/mod.rs, src/rvsdg/to_cfg.rs, src/util.rs, tree_in_context/src/schema_helpers.rs, tree_in_context/src/typechecker.rs
This PR implements the last missing piece in the translation code, converting the Tree IR to an RVSDG.
It also runs all the tests (excluding ones involving memory) on the full compiler.
=> Implement Tree -> RVSDG Translation

tree_in_context/src/add_context.rs, tree_in_context/src/lib.rs, tree_in_context/src/schema_helpers.rs, tree_in_context/src/to_egglog.rs, tree_in_context/src/utility/in_context.egg
This PR adds a rust function that adds context to the original program added to the egraph. This allows the first version of the program to have full contextual information.
We can then use egglog rules to create contexts we need later.
This also makes the generated egglog file much smaller by sharing common sub-expressions.
=> Rust context creation

Cargo.lock, Cargo.toml, tree_in_context/Cargo.toml, tree_in_context/src/schedule.egg, tree_in_context/src/schema.egg, tree_in_context/src/utility/in_context.egg, tree_in_context/src/utility/in_context.rs
This PR improves the context rules, with fine-grained control of how deep to copy.
It also fixes our saturation issues by keeping track of a list of eclasses already visited, and subsuming rows that have encountered a cycle.
=> Context rules with fine-grained control of how deep to copy

src/lib.rs, src/rvsdg/to_dag.rs, src/util.rs, tests/files.rs, tree_in_context/src/ast.rs, tree_in_context/src/interpreter.rs, tree_in_context/src/lib.rs, tree_in_context/src/optimizations/body_contains.rs, tree_in_context/src/schema.rs, tree_in_context/src/typechecker.rs, tree_in_context/src/utility/in_context.rs, tree_in_context/src/utility/subst.rs
This PR fixes up the interpreter to work with the DAG IR. It does so by caching results for evaluating nodes based on the Rc pointer so that they are evaluated just once.
=> Interpreter for DAG IR

dag_in_context/src/from_egglog.rs, src/util.rs
This PR makes the optimizer add context nodes before sending the program to egglog.
To ensure linearity of the state edge on the way back, it removes these context nodes again. This is a hack that should be fixed by a linearity-preserving extractor in the future. Right now, eggcc assumes the extracted program uses memory linearly.
=> Add context before sending to egglog

dag_in_context/src/from_egglog.rs, dag_in_context/src/schema.rs, dag_in_context/src/to_egglog.rs, dag_in_context/src/typechecker.rs, src/rvsdg/to_dag.rs, tests/repro-conversion-bug-loop.bril
The RVSDG->DAG pass wasn't maintaining the sharing invariant (that sub-terms that are equal must be shared using the same Rc<Expr> poitner).
This PR fixes that.
It also fixes up typechecking to do proper caching based on the argument type
=> Fix bug in sharing invariant via translation to Term and back again

dag_in_context/src/ast.rs, dag_in_context/src/interval_analysis.rs, dag_in_context/src/lib.rs, dag_in_context/src/optimizations/constant_fold.rs, dag_in_context/src/optimizations/purity_analysis.rs, dag_in_context/src/optimizations/switch_rewrites.rs, dag_in_context/src/schedule.egg, dag_in_context/src/type_analysis.rs, dag_in_context/src/utility/context-prop.egg, dag_in_context/src/utility/in_context.egg, dag_in_context/src/utility/in_context.rs, dag_in_context/src/utility/subst.egg, dag_in_context/src/utility/subst.rs, dag_in_context/src/utility/util.egg
This PR tweaks the substitution rules to preserve `InIf` contexts. Before, it would throw these away (which is unsound).
It also adds back in the context-prop rules to normalize terms, pushing context to leaf nodes.
=> Context-preserving substitution

dag_in_context/src/ast.rs, dag_in_context/src/utility/util.egg, src/rvsdg/to_dag.rs, tests/snapshots/files__collatz-optimize.snap, tests/snapshots/files__collatz_redundant_computation-optimize.snap, tests/snapshots/files__range_check-optimize.snap
This makes the `parallel!` macro nest to the right and adds a canonicalization rule to the optimizer.
=> Fix parallel to nest like a linked list

dag_in_context/src/interval_analysis.egg
I wish that we got an error instead of a lack of saturation. We should think of some sort of check we can do
=> Fix soundness bug- unioning no context with something that has context

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/schema.egg, dag_in_context/src/utility/in_context.egg, dag_in_context/src/utility/subst.egg
Fixes an extraction bug where things were wrong when a node's children were ignored.
=> Fix get node cost bug

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/interval_analysis.egg, dag_in_context/src/lib.rs, dag_in_context/src/type_analysis.egg
Implements a cost model for all constructors and relations and datatypes using a match statement and a trait.
It is concerning to me that none of the snapshots changed, but maybe it's fine.
=> Implement cost model

dag_in_context/src/greedy_dag_extractor.rs
Previously, the DAG extractor relied on the iteration order of HashMaps.
I tested this with the following (previously, `fib_recursive-optimize` was nondeterministic and occasionally failed snapshot tests).
```
for _ in {1..100}; do
if ! cargo test -r fib_recursive-optimize; then
exit 1
fi
done
```
=> Make DAG extractor deterministic

src/rvsdg/from_cfg.rs, src/rvsdg/mod.rs, src/rvsdg/rvsdg2svg.rs, src/rvsdg/tests.rs, src/rvsdg/to_cfg.rs, src/rvsdg/to_dag.rs
We should just be using Project(0,...).
Sending this before looking into some more changes to rvsdg=>cfg.
=> Remove `Operand::Id` from RVSDG type.

dag_in_context/src/optimizations/loop_unroll.egg, tests/snapshots/files__loop_pass_through-optimize.snap, tests/snapshots/files__strong_loop-optimize.snap
This is the only place where NoContext is used in optimizations. Since we are converting from NoContext to InFunc as the "base" context, we need to make sure our optimizations do not rely on it in critical ways.
=> Remove dependency on NoContext in loop unrolling

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/lib.rs, dag_in_context/src/to_egglog.rs, src/util.rs, tests/snapshots/files__loop_pass_through-optimize.snap
If we change the schema, it'll be fine because we'll get an error that something wasn't extractable.
I also optimized the extraction algorithm to not consider parents that have infinite cost
=> Remove list of helpers from extraction

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/lib.rs, dag_in_context/src/linearity.rs, dag_in_context/src/schema_helpers.rs
The main change in this PR is to check the sort of nodes during the reachability query.
Other than that, this PR refactors costsets to get more sharing.
This PR reduces memory usage by 10x on hard benchmarks
=> Improve extraction's memory usage by filtering to correct types

dag_in_context/src/lib.rs, dag_in_context/src/optimizations/loop_invariant.rs, dag_in_context/src/optimizations/mod.rs, dag_in_context/src/optimizations/peepholes.egg, dag_in_context/src/optimizations/peepholes.rs, dag_in_context/src/optimizations/switch_rewrites.egg, dag_in_context/src/optimizations/switch_rewrites.rs, dag_in_context/src/schedule.rs, tests/snapshots/files__block-diamond-optimize.snap, tests/snapshots/files__implicit-return-optimize.snap, tests/snapshots/files__loop_hoist-optimize.snap, tests/snapshots/files__loop_if-optimize.snap, tests/snapshots/files__loop_with_mul_by_inv-optimize.snap, tests/snapshots/files__unroll_multiple_4-optimize.snap
This change starts a basic peephole optimization files. Most moderately complex peepholes I've found rely on things like shifting operators, sign extensions, etc. None of those can be done at the bril level (but note that LLVM will take advantage of them with optimizations turned on!)
Still, these probably don't hurt. I've added in some rules for forwarding predicates for ifs. Let me know if I'm using contexts correctly here.
=> Add some basic peepholes

.github/workflows/Test.yml, src/util.rs
This is to get us closer to an apples-to-apples comparison with LLVM, given that
most of its peepholes can't be written as rewrites on pure bril.
=> Peepholes in nonopt llvm

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/linearity.rs, dag_in_context/src/schedule.rs, tests/snapshots/files__mem_loop_store_forwarding-optimize.snap
Finding multiple terms for the same eclass results in linearity bugs. This PR fixes that.
=> Fix multiple terms per eclass bug in extraction

src/util.rs, tests/files.rs
This PR refactors the testing of benchmarks to increase sharing of work. Now each benchmark is only optimized once instead of twice. Also, the resulting binaries are executed once per treatment instead of twice.
Brillift is still tested on our smaller tests, but is disabled for the benchmarks.
Overall, this makes running tests about twice as fast
=> Improve perf of testing by increasing sharing, disabling brilift

benchmarks/for_debugging/dump_all.sh, benchmarks/for_debugging/dump_one.sh
See the output here:
https://github.com/egraphs-good/eggcc/tree/script-output/benchmarks/for_debugging/passing
To regenerate, go to `benchmarks/for_debugging` then:
```
./dump_one.sh ../passing/bril/core/bitshift.bril passing/bril/core
./dump_all.sh
```
=> Add script to dump llvm/eggccir for benchmarks

infra/nightly-resources/previousRuns.js, infra/profile.py
We were seeing this error:
If there was no previous run to compare to
Turns out, there wasn't a `main` run in the last 30 runs, so the slice of previous runs we returned didn't have a `main` run.
Fix is to make sure we have at least on `main` run in the slice.
=> Fix frontend crash error

infra/generate_line_counts.py, infra/nightly-resources/data.js, infra/nightly-resources/handlers.js, infra/nightly.sh, infra/profile.py
The latest nightly ([link](https://nightly.cs.washington.edu/reports/eggcc/1716340359:nightly:main:30dbf39f86/)) is broken because the profile.json is huge (half a gig!)
To mitigate, we should store the LLVM separately for each run mode and benchmark
This has the added benefit that we can periodically go delete these files from nightly without losing the rest of the profile info
=> Store LLVM separately on nightly

src/cfg/to_bril.rs, src/rvsdg/snapshots/eggcc__rvsdg__tests__rvsdg_state_mem_to_cfg_more_blocks_snapshot.snap, tests/files.rs, tests/snapshots/files__branch_duplicate_work-optimize.snap, tests/snapshots/files__diamond-optimize.snap, tests/snapshots/files__fib_recursive-optimize.snap, tests/snapshots/files__impossible_if-optimize.snap, tests/snapshots/files__mem_simple_redundant_load-optimize.snap, tests/snapshots/files__range_check-optimize.snap, tests/snapshots/files__range_splitting-optimize.snap, tests/snapshots/files__sqrt-optimize.snap
Discussed this a bit offline. The goal here is to generate somewhat cleaner code. The snapshot diffs have some good examples; a further refinement we might explore is to keep the jumps in place when the exit block has nontrivial logic in it (to avoid duplication).
=> Replace jumps to the exit block with rets.

infra/generate_cfgs.py, infra/generate_line_counts.py, infra/nightly-resources/handlers.js, infra/nightly-resources/index.html, infra/nightly-resources/index.js, infra/nightly-resources/llvm.html, infra/nightly-resources/llvm.js, infra/nightly-resources/stylesheet.css, infra/nightly-resources/table.html, infra/nightly.sh, infra/profile.py
=> Show CFGs on Nightly

dag_in_context/src/optimizations/switch_rewrites.egg, tests/passing/small/max.bril, tests/passing/small/min.bril, tests/snapshots/files__max-optimize.snap, tests/snapshots/files__min-optimize.snap
Doesn't result in big changes to benchmarks yet because of the branch thing that @Alex-Fischman is working on.
But I tested on the commit that Alex sent me, and `min.bril` correctly optimizes to
```
@main(v0: int, v1: int) {
.b2_:
v3_: int = smin v0 v1;
print v3_;
}
```
=> Rewrite if a </> b then a else b to min/max

infra/nightly-resources/data.js, infra/nightly-resources/handlers.js, infra/nightly-resources/index.js, infra/nightly-resources/llvm.html, infra/nightly-resources/table.js, infra/profile.py
1. Fix expand/collapse for llvm IR
2. link to bril (on github) for each benchmark
=> [Nightly] Small fixes

proofs/proofs.v
Add a mechanized formal semantics for eggcc IR*, as well as proofs of:
- If context introduction
- `(If pred in then else)` is equivalent to `(If pred in (Ctx (InThen pred in) then) (Ctx (InElse pred in) else)`
- Context pushdown
- `(Ctx a (PureOp e))` is equivalent to `(PureOp (Ctx a e))`
- `(Ctx a (If pred in then else))` is equivalent to `(If (Ctx a pred) (Ctx a in) then else)`
- `(Ctx a (DoWhile in pred out))` is equivalent to `(DoWhile (Ctx a in) pred out)`
- Constant input substitution
- `(Ctx (InThen pred (Const c)) Arg)` is equivalent to `(Ctx (InThen pred (Const c)) (Const c))`
*See here for more explanation of the modeled IR/semantics, which are more general (context nodes, arbitrary pure ops) than those actually used in eggcc now: …
=> Mechanized semantics and proofs

README.md
On Mac, I had to do `brew upgrade` for `make` to work. Added this in the readme in a new section.
=> Add a troubleshooting section to the README.md

dag_in_context/src/optimizations/loop_unroll.egg, dag_in_context/src/optimizations/memory.egg, dag_in_context/src/optimizations/passthrough.egg
Porting part of #617 to the main.
Many of our bottleneck queries can indeed be improved because they have common sub-expressions. A better egglog should do this optimization automatically but it currently does not.
=> Eliminate common subexpressions in our queries

src/rvsdg/optimize_direct_jumps.rs, tests/snapshots/files__collatz_redundant_computation-optimize-sequential.snap, tests/snapshots/files__collatz_redundant_computation-optimize.snap, tests/snapshots/files__fib_recursive-optimize-sequential.snap, tests/snapshots/files__fib_recursive-optimize.snap, tests/snapshots/files__gamma_condition_and-optimize-sequential.snap, tests/snapshots/files__gamma_condition_and-optimize.snap, tests/snapshots/files__if_dead_code_nested-optimize-sequential.snap, tests/snapshots/files__if_dead_code_nested-optimize.snap, tests/snapshots/files__mem_loop_store_forwarding-optimize-sequential.snap, tests/snapshots/files__mem_loop_store_forwarding-optimize.snap, tests/snapshots/files__recurse_once-optimize-sequential.snap, tests/snapshots/files__recurse_once-optimize.snap, tests/snapshots/files__simple_recursive-optimize-sequential.snap, tests/snapshots/files__simple_recursive-optimize.snap, tests/snapshots/files__small-collatz-optimize-sequential.snap, tests/snapshots/files__small-collatz-optimize.snap, tests/snapshots/files__sqrt_small-optimize-sequential.snap, tests/snapshots/files__sqrt_small-optimize.snap
This change simplifies the empty block optimizer, and also adds a new pass that detects blocks that only contain identity operators. This cuts down on intermediate blocks.
=> Better cfg optimizer for empty blocks

infra/generate_cfgs.py
Old filenames were still brittle
=> Fix cfg for eggcc modes

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/lib.rs, tests/snapshots/files__fib_recursive-optimize-sequential.snap, tests/snapshots/files__fib_recursive-optimize.snap, tests/snapshots/files__implicit-return-optimize-sequential.snap
Pr #660 separated the egraph's optimization of different functions. Turns out this makes everything a lot slower, perhaps due to sharing of types and other subexpressions.
This PR changes it back to batching all the functions together, but keeps extraction as per-function. This allows the extractor in the future to be function-aware, making recursive calls expensive.
It also optimizes extraction to find reachable regions instead of extracting everything in the egraph.
=> Go back to batching all fns from the program together

benchmarks/passing/bril/long/function_call.bril, infra/generate_cfgs.py, infra/nightly-resources/chart.js, infra/nightly-resources/data.js, infra/nightly-resources/index.js, infra/nightly-resources/llvm.js, infra/profile.py, src/main.rs, src/util.rs
This PR allows eggcc to run LLVM with separate optimization levels for the middle-end and lowering to a binary. The idea is to give us a more fair comparison in the nightly because LLVM won't be doing platform-specific optimization, so we compare more directly to the llvm middle-end optimizer. 
It leaves in the normal O3 run as `llvm-O3-O3`.
=> Separate llvm compilation into optimization and lowering

install_ubuntu.sh
I am building eggcc in a fresh Ubuntu virtual machine and got the following errors
```
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lstdc++
```
The second one is fixed because I don't have a C++ compiler installed, so I immediately fixed it. I found the solution to the first error with [this StackOverflow post](https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz).
=> Fix dependency

infra/jitter.py, infra/nightly-resources/chart.js, infra/nightly-resources/data.js, infra/nightly-resources/handlers.js, infra/nightly-resources/index.html, infra/nightly-resources/stylesheet.css
This PR changes nightly to use "normalized times" instead of speedup. This allows us to make meaningful std dev error bars
It also changes the jitter plot to use normalized times.
=> Use normalized times instead of speedup in nightly

dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/schedule.rs, tests/snapshots/files__if_in_loop-optimize.snap, tests/snapshots/files__loop_strength_reduction-optimize.snap
This is the loop strength reduction example after this PR
The cost of this is now computed as 27026, which is roughly 300 * (50 + 10 + 10 + 10 + 10) (the cost of add and lt is 10, and of print is 50)
Unfortunately, in this example, only LSR is applied, but not loop unrolling (which used to apply), because we only run our optimization twice. We can either bump the #iter opt is applied or the #batch to have loop unrolling and LSR both applied
=> Fixes the cost calculation which counts all `Mul` in a region only once

Cargo.lock, Cargo.toml, infra/profile.py, src/main.rs, src/util.rs
The current code in main doesn't properly measure llvm compile time, it measures calling llvm multiple times
This one makes it just measure the optimization llvm does without lowering, making it a fairer comparison
=> Measure proper llvm compile times

Cargo.lock, Cargo.toml, benchmarks/passing/raytrace.rs, dag_in_context/src/ast.rs, dag_in_context/src/from_egglog.rs, dag_in_context/src/greedy_dag_extractor.rs, dag_in_context/src/interpreter.rs, dag_in_context/src/interval_analysis.egg, dag_in_context/src/optimizations/peepholes.egg, dag_in_context/src/optimizations/purity_analysis.egg, dag_in_context/src/pretty_print.rs, dag_in_context/src/schema.egg, dag_in_context/src/schema.rs, dag_in_context/src/schema_helpers.rs, dag_in_context/src/type_analysis.egg, src/rvsdg/from_dag.rs, src/rvsdg/to_dag.rs, tests/passing/small/if_invariant_dont_pull_out.rs, tests/slow/raytracewithscreen.rs, tests/snapshots/files__branch_hoisting-optimize.snap, tests/snapshots/files__if_invariant_dont_pull_out-optimize-sequential.snap, tests/snapshots/files__if_invariant_dont_pull_out-optimize.snap
```
// ARGS: 20
fn unrelated_fn(input: i64, res: i64) -> i64 {
return input / (res / 3);
}
fn other_unrelated_fn(input: i64, res: i64) -> i64 {
return res / (input / 5);
}
fn main(input: i64) {
let mut res: i64 = abs(input) * 2;
if (input > 0) {
res = res + abs(input) - input;
res = unrelated_fn(input, res);
} else {
res = res + abs(input) + input;
res = other_unrelated_fn(input, res);
}
println!("{}", res);
}
```
Output bril:
```
@unrelated_fn(v0: int, v1: int): int {
.b2_:
c3_: int = const 3;
v4_: int = div v1 c3_;
v5_: int = div v0 v4_;
ret v5_;
}
@other_unrelated_fn(v0: int, v1: int): int {
.b2_:
c3_: int = const 5;
v4_: int = div v0 c3_;
v5_: int = div v1 v4_;
ret v5_;
}
@main(v0: int) {
.b1_:
c2_: int = const 0;
v3_: bool = gt v0 c2_;
v4_: int = abs v0;
c5_: int = const 2;
v6_: int …
```
=> Add `abs` and make Oliver's example work

dag_in_context/src/interval_analysis.egg, dag_in_context/src/lib.rs, dag_in_context/src/optimizations/conditional_invariant_code_motion.egg, dag_in_context/src/optimizations/peepholes.egg, dag_in_context/src/schedule.rs, tests/passing/small/if_invariant_do_pull_out.rs, tests/passing/small/pull_out_small.rs, tests/snapshots/files__block-diamond-optimize-sequential.snap, tests/snapshots/files__fib_recursive-optimize-sequential.snap, tests/snapshots/files__fib_recursive-optimize.snap, tests/snapshots/files__if_invariant_do_pull_out-optimize-sequential.snap, tests/snapshots/files__if_invariant_do_pull_out-optimize.snap, tests/snapshots/files__if_invariant_dont_pull_out-optimize-sequential.snap, tests/snapshots/files__pull_out_small-optimize-sequential.snap, tests/snapshots/files__pull_out_small-optimize.snap, tests/snapshots/files__reassoc-optimize-sequential.snap, tests/snapshots/files__select-optimize-sequential.snap
With this rule:
```
(rule ((Bop (Mul) (Uop (Abs) x) (Const (Int 3) ty ctx)))
((panic "good")) :ruleset peepholes)
```
we can tell that the optimization is firing and finding the way to pull `res = res + abs(input)` out of both branches, but due to extraction issues, we're not extracting that program.
=> Conditional Invariant Code Motion (Pull Out)

dag_in_context/src/lib.rs, dag_in_context/src/optimizations/conditional_push_in.egg, dag_in_context/src/schedule.rs, tests/passing/small/if_push_in.rs, tests/snapshots/files__block-diamond-optimize-sequential.snap, tests/snapshots/files__fib_recursive-optimize-sequential.snap, tests/snapshots/files__fib_recursive-optimize.snap, tests/snapshots/files__gamma_condition_and-optimize.snap, tests/snapshots/files__if_invariant_do_pull_out-optimize.snap, tests/snapshots/files__if_push_in-optimize-sequential.snap, tests/snapshots/files__if_push_in-optimize.snap, tests/snapshots/files__reassoc-optimize-sequential.snap, tests/snapshots/files__select-optimize-sequential.snap
Although, we don't remove the original input, so it ends up actually looking like this:
This extra (now unused) input will hopefully get cleaned up with Oliver's new dead-code-aware extraction.
=> Conditional Push In

dag_in_context/src/lib.rs, dag_in_context/src/schema.egg, infra/graphs.py, infra/nightly-resources/chart.js, infra/nightly-resources/data.js, infra/nightly-resources/index.js, infra/profile.py, src/main.rs, src/util.rs
Remove a ruleset with `--ablate RULESET`
To see a `localnightly.sh` with ablated versions, set the following string in `profile.py` to non-empty (e.g. "loop-inv-motion").
```
TO_ABLATE = "" # change to a ruleset to ablate
```
=> Ablate any ruleset
